### ISSUE TITLE
Filter returning more than 1 message

### ISSUE THREAD

**Issue by alexschwantes** [tyrrellsystems/node-red-contrib-simple-weekly-scheduler#15]
The Filter is not working as expected.

If I create 3 allowed time periods in the calendar, every time the filter receives an input it seems like it is outputting 3 messages on the second node (one for each time period created). I would have expected it to output only 1 message on either the first node OR the second node. 

I've made some changes to fix this and will submit a bull request.

**Comment by hardillb** [comment]
Can you post a sample flow that demonstrates the problem

**Comment by alexschwantes** [comment]
Sure thing. There are a number of schedules present in this scheduler node. When you trigger an input it should only output 1 message, either success or failure, but instead it outputs a number of messages.

`[{"id":"4481daed.b74b64","type":"debug","z":"77d92c58.d74de4","name":"success","active":true,"console":"false","complete":"true","x":497,"y":220,"wires":[]},{"id":"c9d1c9c2.5e3f18","type":"debug","z":"77d92c58.d74de4","name":"failure","active":true,"console":"false","complete":"true","x":494,"y":268,"wires":[]},{"id":"50336f64.ea321","type":"time-filter","z":"77d92c58.d74de4","events":"[{\"start\":\"2009-05-09T22:00:00.000Z\",\"end\":\"2009-05-10T02:00:00.000Z\",\"title\":\"\",\"id\":0},{\"start\":\"2009-05-10T15:45:00.000Z\",\"end\":\"2009-05-10T21:15:00.000Z\",\"title\":\"\",\"id\":1},{\"start\":\"2009-05-10T22:00:00.000Z\",\"end\":\"2009-05-11T02:00:00.000Z\",\"title\":\"\",\"id\":2},{\"start\":\"2009-05-11T13:30:00.000Z\",\"end\":\"2009-05-11T20:00:00.000Z\",\"title\":\"\",\"id\":3},{\"start\":\"2009-05-11T22:00:00.000Z\",\"end\":\"2009-05-12T02:00:00.000Z\",\"title\":\"\",\"id\":4},{\"start\":\"2009-05-12T08:00:00.000Z\",\"end\":\"2009-05-12T17:30:00.000Z\",\"title\":\"\",\"id\":5},{\"start\":\"2009-05-13T12:45:00.000Z\",\"end\":\"2009-05-13T17:30:00.000Z\",\"title\":\"\",\"id\":6}]","topic":"","central":"","name":"","x":299,"y":242,"wires":[["4481daed.b74b64"],["c9d1c9c2.5e3f18"]]},{"id":"e831a93b.cea668","type":"inject","z":"77d92c58.d74de4","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":101,"y":234,"wires":[["50336f64.ea321"]]}]`

**Comment by hardillb** [comment]
Sorry for the delay, been busy.

With this test flow I'm still seeing multiple output with your #16  pull request

**Comment by hardillb** [comment]
Ignore that last update I'd messed up checking your code out
