### ISSUE TITLE
Central list url dissapear

### ISSUE THREAD

**Issue by johntrygve** [tyrrellsystems/node-red-contrib-simple-weekly-scheduler#21]
Hi, 
I think of using this scheduler because of the central list json function. 
The problem is: If I paste a link to a json file and press save, it just dissapears. If i open the node UI again it is gone. I write the url like this:   http://www.******/jth/test.json 
and the content is the same as in the example.
I hope some of you can test it.
Thanks,

-John

**Comment by hardillb** [comment]
I must admit that functionality didn't get a lot of testing when it got put together. I'll try and find some time for a look at it later in the week.
