### ISSUE TITLE
Central List not updating schedule

### ISSUE THREAD

**Issue by frigidplatypus** [tyrrellsystems/node-red-contrib-simple-weekly-scheduler#28]
I have copied the example json, but the scheduler is not updating to reflect the file.

Node-Red v0.18.2

**Comment by nuali** [comment]
Almost one year ago and I ran into the same problem.
I created a 'http in node' to serve the central list, which works fine if I call it via the browser (plus I can see the GET-request at the debug tab), but there's no (GET) request fired by the scheduler and I waited several times for more than 10 minutes.

Did you solve it somehow?

**Comment by nuali** [comment]
I figured it out, 'hassio' as domain doesn't work, because it points to the internal docker ip and port 1880 isn't open. It works well with the "external" ip.
