### ISSUE TITLE
msg error when it first starts

### ISSUE THREAD

**Issue by davidoc85** [tyrrellsystems/node-red-contrib-simple-weekly-scheduler#7]
The scheduler is connected to a Ind Digital Out bricklet ("FCU Enable").  When it is deployed or it first starts the tinkerforge node gives out the exception:

27/10/2016, 13:26:53 FCU Enable msg : errorTypeError: Cannot read property 'setValue' of undefined

After this it works ok and no more error messages are shown.

**Comment by hardillb** [comment]
If the message is tagged with FCU Enable then it will be a problem with the Tinkerforge node not the scheduler

**Comment by davidoc85** [comment]
Here is the example.  The error comes only when the scheduler is connected:

[{"id":"c60b2541.e28da","type":"TinkerForge Digital-Out","z":"cd32699c.55091","device":"7244c4bd.8b91f4","sensor":"rEt","topic":"","name":"FCU Enable","x":977,"y":207,"wires":[]},{"id":"5781a616.a35228","type":"change","z":"cd32699c.55091","name":"true to json","rules":[{"t":"change","p":"payload","pt":"msg","from":"true","fromt":"bool","to":"[1,0,0,0]","tot":"json"}],"action":"","property":"","from":"","to":"","reg":false,"x":794,"y":192,"wires":[["c60b2541.e28da"]]},{"id":"3e46dc11.4a3c34","type":"change","z":"cd32699c.55091","name":"false to json","rules":[{"t":"change","p":"payload","pt":"msg","from":"false","fromt":"bool","to":"[0,0,0,0]","tot":"json"}],"action":"","property":"","from":"","to":"","reg":false,"x":794,"y":227,"wires":[["c60b2541.e28da"]]},{"id":"e1429a8f.bbce28","type":"Or","z":"cd32699c.55091","topic":"","inputCount":"4","x":605,"y":210,"wires":[["5781a616.a35228","3e46dc11.4a3c34","e23dea13.06b528","b7d269d3.04b6f8"]]},{"id":"c3acd68c.9e51a8","type":"time-planner","z":"cd32699c.55091","events":"[{\"start\":\"2009-04-27T07:30:00.000Z\",\"end\":\"2009-04-27T17:00:00.000Z\",\"title\":\"\",\"id\":0},{\"start\":\"2009-04-28T07:30:00.000Z\",\"end\":\"2009-04-28T17:00:00.000Z\",\"title\":\"\",\"id\":1},{\"start\":\"2009-04-29T07:30:00.000Z\",\"end\":\"2009-04-29T17:00:00.000Z\",\"title\":\"\",\"id\":2},{\"start\":\"2009-04-30T07:30:00.000Z\",\"end\":\"2009-04-30T17:00:00.000Z\",\"title\":\"\",\"id\":3},{\"start\":\"2009-05-01T07:30:00.000Z\",\"end\":\"2009-05-01T17:00:00.000Z\",\"title\":\"\",\"id\":4}]","topic":"","central":"","startPayload":"true","startPayloadType":"str","endPayload":"false","endPayloadType":"str","name":"Timezone","x":113,"y":194,"wires":[["f6f5871a.6aad4","e1429a8f.bbce28"]]},{"id":"1355418b.cfed5e","type":"hysteresis","z":"cd32699c.55091","setpoint":"16","deadband":"0.25","x":120.5,"y":239,"wires":[["e1429a8f.bbce28"]]},{"id":"40d3b022.36e15","type":"mqtt in","z":"cd32699c.55091","name":"PIR","topic":"PIR/1","qos":"0","broker":"27d6495b.32c1ae","x":107,"y":286,"wires":[["e1429a8f.bbce28"]]},{"id":"3d23b60.34eb9ca","type":"TinkerForge PTC","z":"cd32699c.55091","device":"7244c4bd.8b91f4","sensor":"z8a","pollTime":"30","name":"ReturnTemp","topic":"Ret","x":175,"y":53,"wires":[["1fd863e5.a8894c","1355418b.cfed5e"]]},{"id":"e23dea13.06b528","type":"debug","z":"cd32699c.55091","name":"Enable","active":true,"console":"false","complete":"payload","x":783,"y":160,"wires":[]},{"id":"7244c4bd.8b91f4","type":"TinkerForgeConfig","z":"","host":"192.168.0.4","port":"4223","name":""},{"id":"27d6495b.32c1ae","type":"mqtt-broker","z":"","broker":"localhost","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"willTopic":"","willQos":"0","willPayload":"","birthTopic":"","birthQos":"0","birthPayload":""}]

**Comment by hardillb** [comment]
OK, I've just looked at the code, this is problem with the Tinkerforge node not the Scheduler. It's a race condition between the first message arriving and the Tinkerforge node being able to connect to the bricklet.

**Comment by hardillb** [comment]
Closing this as I've opened a new one against the right project
