### ISSUE TITLE
Scheduler no value eventhough specific days schedule should be false

### ISSUE THREAD

**Issue by davidoc85** [tyrrellsystems/node-red-contrib-simple-weekly-scheduler#8]
Got a similar issue but with false.
If there is no schedule a false should be sent, because at the moment it does not send anything so the OR logic is assuming it is true.

Example: Tuesday the time schedule only starts at 15:00 and it is currently 14:30

[export.txt](https://github.com/tyrrellsystems/node-red-contrib-simple-weekly-scheduler/files/578404/export.txt)

**Comment by hardillb** [comment]
OK, that makes sense I'll have a look

**Comment by hardillb** [comment]
Does it matter if I just send the payload and miss out the event info (to save having to work out what the last event would have been)

**Comment by hardillb** [comment]
version 0.0.6 pushed to npm with this fix
